### ISSUE TITLE
compile error linux/stdarg.h not found

### ISSUE THREAD

**Issue by apurvk4** [lwfinger/realtek_bluetooth#4]
tried to build it on  5.19.16-76051916-generic kernel and got this error .
```
 ./include/linux/kernel.h:14:10: fatal error: linux/stdarg.h: No such file or directory
   14 | #include <linux/stdarg.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```
I am getting this error on compiling any dkms module on this kernel.
I am bit new to this stuff.

**Comment by lwfinger** [comment]
Your system has a problem. That include is not mentioned anywhere in the code, and that driver builds on kernel 6.1.0-rc1 for me.
